[package]
name = "charles/bouncy-banana-defense"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "0.1.0"

[dependencies]
Knit = "sleitnick/knit@^1.5.1"
input = "sleitnick/input@2.1.1"
janitor = "howmanysmall/janitor@1.15.1"
signal = "sleitnick/signal@1.5.0"
spr = "blackjackiee/spr@1.1.3"
